language: node_js

node_js:
  - "4"
  - "6"
  - "8"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn --version
  - node_modules/.bin/builder run check-ci

  # Prune deps to just production and ensure we can still build
  - rm -rf node_modules
  - yarn install --production
  - node_modules/.bin/builder run build
