language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.2"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

env:
  matrix:
    - NPM_3=true
    - NPM_3=false

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Potentially update to npm 3
  - 'if [ "$NPM_3" = true ]; then npm install -g npm@3; else true; fi'

script:
  # Check archetype.
  - npm --version
  - npm run builder:check

  # Initialize a fresh project from templates
  - npm install -g builder-init
  - mkdir .builder-init-tmp
  - cd .builder-init-tmp
  - >-
    builder-init $PWD/.. --prompts='{
    "packageName":"whiz-bang",
    "packageGitHubOrg":"Acme",
    "packageDescription":"Whiz Bang",
    "licenseDate":"2016",
    "licenseOrg":"Acme",
    "destination":"whiz-bang"}'

  # Run initialized project's own CI
  - cd whiz-bang
  - npm install
  - node_modules/.bin/builder run check-ci
  - npm prune --production
  - node_modules/.bin/builder run build
