language: node_js

node_js:
  - "4"
  - "6"
  - "8"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # Check archetype.
  - yarn --version
  - yarn run builder:check

  # Create linked modules with _only_ prod dependencies (sometimes errors without).
  - yarn prune --production && yarn link
  - cd dev && yarn prune --production && yarn link && cd ..

  # Initialize a fresh project from templates
  - yarn install -g builder-init
  - mkdir .builder-init-tmp
  - cd .builder-init-tmp
  - >-
    builder-init $PWD/.. --prompts='{
    "packageName":"whiz-bang",
    "packageGitHubOrg":"Acme",
    "packageDescription":"Whiz Bang",
    "licenseDate":"2016",
    "licenseOrg":"Acme",
    "destination":"whiz-bang"}'

  # Run initialized project's own CI with npm link'ed archetypes.
  - cd whiz-bang
  - yarn link builder-react-component
  - yarn install
  - node_modules/.bin/builder run build
  # TODO: Install dev archetype and run checks.
  #- yarn link builder-react-component-dev
  #- node_modules/.bin/builder run check-ci
